### ISSUE TITLE
How to get service from different widget?

### ISSUE THREAD

**Issue by frendcarlo** [mintware-de/catalyst_builder#17]
How do I get service from other widget using provider?  If I keep on passing provider, seems like not a proper way although it works if I declare provider as public.  Any Idea how you do this? 

`// Import the service provider 
import 'my_entrypoint.catalyst_builder.g.dart';

@GenerateServiceProvider()
void main() {
  // Create a new instance of the service provider
  var provider = DefaultServiceProvider();
  
  // Boot it to wire services
  provider.boot();

  // Resolve a service.
  var myService1 = provider.resolve<MyService>();

  // Inferred types are also supported
  MyService myService2 = provider.resolve();

  myService2.init();

  runApp(const MyApp());
} 

// I have more widgets that I need to get those services
class MyApp extends statelessWidget {
  final pushService = provider.resolve<PushService>();

  MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
     return Scaffold(
         body: Container() );    
  }
}

`

**Comment by devtronic** [comment]
What is your specific intent? You can inject the service by passing it to the constructor or register the provider itself as a service and pass it to the widget where you can dynamically resolve the service you need 🙂 

Maybe this project helps you with autowiring of screens: https://github.com/mintware-de/explorator
